language: php

sudo: required

services:
    - docker

php:
    - 5.5
    - 5.4
    - 5.3

branches:
  only:
      - master

before_script:
    - sudo apt-get install -y -qq libssh2-1-dev libssh2-php
    - printf "\n" | pecl install -f ssh2-beta
    - cd Tests

script: make

