
language: php
php:
    - 5.5
    - 5.4
    - 5.3

branches:
    only:
        - master

services:

before_script:
    # install ftp server and ssh dependencies
    - sudo apt-get update
    - sudo apt-get install -y --force-yes proftpd-basic libssh2-1-dev
    - printf "\n" | pecl install channel://pecl.php.net/ssh2-0.12

    # edit ftp server settings: root user to user directory, display hidden files
    - sudo bash -c 'cat /etc/proftpd/proftpd.conf | sed "s/^.*DefaultRoot.*$/DefaultRoot ~/" | sed "s/^.*ListOptions.*$/ListOptions \"-la\"/" > /etc/proftpd/proftpd.conf.tmp'
    - sudo mv /etc/proftpd/proftpd.conf.tmp /etc/proftpd/proftpd.conf
    - sudo /etc/init.d/proftpd restart

    # create test user account with 'testpass' password
    - sudo useradd -m -p co.yjyxRTlonU testuser

    # add authorized keys
    - sudo rm -rf /home/testuser
    - sudo ln -s $TRAVIS_BUILD_DIR/Tests/docker/home /home/testuser
    - sudo chown -R testuser:testuser /home/testuser
    - sudo chmod -R 777 /home/testuser

    # replace host key
    - sudo cp Tests/docker/ssh/ssh_host_rsa_key /etc/ssh

script: phpunit --configuration Tests/PHPUnit.xml Tests/
