language: php
php:
    - 5.5
    - 5.4
    - 5.3

install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq imagemagick graphicsmagick optipng pngcrush jpegoptim jpegtran

script: 
    phpunit --bootstrap Tests/bootstrap.php Tests
