language: php
php:
    - 5.5
    - 5.4
    - 5.3

branches:
  only:
      - master

services:

before_script:
    - printf "\n" | pecl install channel://pecl.php.net/ssh2-0.12

script: phpunit --configuration Tests/PHPUnit.xml Tests/

