language: php

php:
    - 5.5
    - 5.4
    - 5.3

branches:
  only:
      - master

sudo: required

services:
    - docker

before_script:
    - sudo apt-get install -y -qq libssh2-1-dev libssh2-php
    - pecl install -f ssh2-beta < .noninteractive
    - cd Tests

script: make

