language: php
php:
    - 5.5
    - 5.4
    - 5.3

services:
    - mysql

before_script:
    - mysql -e 'create database test_db;'
    - echo "GRANT ALL PRIVILEGES ON test_db.* TO 'test_db_user'@'localhost' IDENTIFIED BY 'test_db_password' WITH GRANT OPTION;" | mysql -u root
    - ls -1 Sql/*.sql | awk '{print "SET FOREIGN_KEY_CHECKS=0;"; print "source",$0; print "SET FOREIGN_KEY_CHECKS=1;";  }' | mysql --batch -utest_db_user -ptest_db_password test_db

script: phpunit --configuration Tests/PHPUnit.xml Tests/

