language: php

sudo: required

services:
    - docker

php:
    - 5.5
    - 5.4
    - 5.3

branches:
  only:
      - master

before_script:
    - sudo apt-get install -y --force-yes libssh2-1-dev
    - printf "\n" | pecl install channel://pecl.php.net/ssh2-0.12
    - cd Tests

script: make

