language: php
php:
    - 5.5
    - 5.4
    - 5.3

services:
    - redis-server
    - memcached

before_script:
    - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script: phpunit --bootstrap Tests/bootstrap.php Tests
