language: php
php:
    - 5.5
    - 5.4

sudo: required

branches:
  only:
      - master

services:
    - docker

before_script:
    - apt-get update -qq
    - apt-get install -y -qq libssh2-1-dev libssh2-php
    - php --ri ssh2
    - cd Tests

script: make

