language: php
php:
    - 5.5
    - 5.4
    - 5.3

sudo: required

branches:
  only:
      - master

services:
    - docker

before_script:
    - sudo apt-get update -qq
    - sudo apt-get install -y -qq libssh2-1-dev libssh2-php php-pear php5-dev
    - printf "\n" | pecl install channel://pecl.php.net/ssh2-0.13
    - cd Tests

script: make

